// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file messageTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "messageTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "message.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace cat
{
namespace middleware
{
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Message_type_identifier(TypeIdentifierPair& type_ids_Message)
{

	ReturnCode_t return_code_Message{eprosima::fastdds::dds::RETCODE_OK};
	return_code_Message =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::Message", type_ids_Message
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_Message)
	{
		StructTypeFlag struct_flags_Message = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE, false, false
		);
		QualifiedTypeName type_name_Message = "cat::middleware::Message";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Message;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Message;
		CompleteTypeDetail detail_Message = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_Message, ann_custom_Message, type_name_Message.to_string()
		);
		CompleteStructHeader header_Message;
		header_Message = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Message);
		CompleteStructMemberSeq member_seq_Message;
		{
			TypeIdentifierPair type_ids_additional_information;
			ReturnCode_t return_code_additional_information{eprosima::fastdds::dds::RETCODE_OK};
			return_code_additional_information =
			    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			        ->type_object_registry()
			        .get_type_identifiers("anonymous_string_unbounded", type_ids_additional_information);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_additional_information)
			{
				{
					SBound bound                 = 0;
					StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
					if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
					   TypeObjectUtils::build_and_register_s_string_type_identifier(
					       string_sdefn, "anonymous_string_unbounded", type_ids_additional_information
					   ))
					{
						EPROSIMA_LOG_ERROR(
						    XTYPES_TYPE_REPRESENTATION,
						    "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type."
						);
					}
				}
			}
			StructMemberFlag member_flags_additional_information = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false
			);
			MemberId member_id_additional_information = 0x00000000;
			bool common_additional_information_ec{false};
			CommonStructMember common_additional_information{TypeObjectUtils::build_common_struct_member(
			    member_id_additional_information,
			    member_flags_additional_information,
			    TypeObjectUtils::retrieve_complete_type_identifier(
			        type_ids_additional_information, common_additional_information_ec
			    )
			)};
			if(!common_additional_information_ec)
			{
				EPROSIMA_LOG_ERROR(
				    XTYPES_TYPE_REPRESENTATION, "Structure additional_information member TypeIdentifier inconsistent."
				);
				return;
			}
			MemberName name_additional_information = "additional_information";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_additional_information;
			ann_custom_Message.reset();
			CompleteMemberDetail detail_additional_information = TypeObjectUtils::build_complete_member_detail(
			    name_additional_information, member_ann_builtin_additional_information, ann_custom_Message
			);
			CompleteStructMember member_additional_information = TypeObjectUtils::build_complete_struct_member(
			    common_additional_information, detail_additional_information
			);
			TypeObjectUtils::add_complete_struct_member(member_seq_Message, member_additional_information);
		}
		{
			TypeIdentifierPair type_ids_protobuf;
			ReturnCode_t return_code_protobuf{eprosima::fastdds::dds::RETCODE_OK};
			return_code_protobuf = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			                           ->type_object_registry()
			                           .get_type_identifiers("anonymous_sequence_byte_unbounded", type_ids_protobuf);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_protobuf)
			{
				return_code_protobuf = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
				                           ->type_object_registry()
				                           .get_type_identifiers("_byte", type_ids_protobuf);

				if(eprosima::fastdds::dds::RETCODE_OK != return_code_protobuf)
				{
					EPROSIMA_LOG_ERROR(
					    XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier unknown to TypeObjectRegistry."
					);
					return;
				}
				bool element_identifier_anonymous_sequence_byte_unbounded_ec{false};
				TypeIdentifier* element_identifier_anonymous_sequence_byte_unbounded{new TypeIdentifier(
				    TypeObjectUtils::retrieve_complete_type_identifier(
				        type_ids_protobuf, element_identifier_anonymous_sequence_byte_unbounded_ec
				    )
				)};
				if(!element_identifier_anonymous_sequence_byte_unbounded_ec)
				{
					EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
					return;
				}
				EquivalenceKind equiv_kind_anonymous_sequence_byte_unbounded = EK_COMPLETE;
				if(TK_NONE == type_ids_protobuf.type_identifier2()._d())
				{
					equiv_kind_anonymous_sequence_byte_unbounded = EK_BOTH;
				}
				CollectionElementFlag element_flags_anonymous_sequence_byte_unbounded = 0;
				PlainCollectionHeader header_anonymous_sequence_byte_unbounded =
				    TypeObjectUtils::build_plain_collection_header(
				        equiv_kind_anonymous_sequence_byte_unbounded, element_flags_anonymous_sequence_byte_unbounded
				    );
				{
					SBound bound                     = 0;
					PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(
					    header_anonymous_sequence_byte_unbounded,
					    bound,
					    eprosima::fastcdr::external<TypeIdentifier>(
					        element_identifier_anonymous_sequence_byte_unbounded
					    )
					);
					if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
					   TypeObjectUtils::build_and_register_s_sequence_type_identifier(
					       seq_sdefn, "anonymous_sequence_byte_unbounded", type_ids_protobuf
					   ))
					{
						EPROSIMA_LOG_ERROR(
						    XTYPES_TYPE_REPRESENTATION,
						    "anonymous_sequence_byte_unbounded already registered in TypeObjectRegistry for a "
						    "different type."
						);
					}
				}
			}
			StructMemberFlag member_flags_protobuf = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false
			);
			MemberId member_id_protobuf = 0x00000001;
			bool common_protobuf_ec{false};
			CommonStructMember common_protobuf{TypeObjectUtils::build_common_struct_member(
			    member_id_protobuf,
			    member_flags_protobuf,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_protobuf, common_protobuf_ec)
			)};
			if(!common_protobuf_ec)
			{
				EPROSIMA_LOG_ERROR(
				    XTYPES_TYPE_REPRESENTATION, "Structure protobuf member TypeIdentifier inconsistent."
				);
				return;
			}
			MemberName name_protobuf = "protobuf";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_protobuf;
			ann_custom_Message.reset();
			CompleteMemberDetail detail_protobuf = TypeObjectUtils::build_complete_member_detail(
			    name_protobuf, member_ann_builtin_protobuf, ann_custom_Message
			);
			CompleteStructMember member_protobuf =
			    TypeObjectUtils::build_complete_struct_member(common_protobuf, detail_protobuf);
			TypeObjectUtils::add_complete_struct_member(member_seq_Message, member_protobuf);
		}
		CompleteStructType struct_type_Message =
		    TypeObjectUtils::build_complete_struct_type(struct_flags_Message, header_Message, member_seq_Message);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
		   TypeObjectUtils::build_and_register_struct_type_object(
		       struct_type_Message, type_name_Message.to_string(), type_ids_Message
		   ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::Message already registered in TypeObjectRegistry for a different type."
			);
		}
	}
}
}  // namespace middleware

}  // namespace cat
