// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file requestsClient.hpp
 * Client implementation for interfaces
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_CLIENT_HPP
#define FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_CLIENT_HPP

#include <memory>

#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/domain/qos/RequesterQos.hpp>

#include "requests.hpp"

namespace cat
{

namespace middleware
{

namespace dds
{

extern eProsima_user_DllExport std::shared_ptr<Requests> create_RequestsClient(
    eprosima::fastdds::dds::DomainParticipant& part,
    char const* service_name,
    eprosima::fastdds::dds::RequesterQos const& qos
);

}  // namespace dds

}  // namespace middleware

}  // namespace cat

#endif  // FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_CLIENT_HPP
