// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file requestsServerImpl.hpp
 * Server implementation for interfaces
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_SERVERIMPL_HPP
#define FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_SERVERIMPL_HPP

#include "requests.hpp"
#include "requestsServer.hpp"

namespace cat
{

namespace middleware
{

namespace dds
{

//{ interface Requests

struct RequestsServerImplementation : public RequestsServer_IServerImplementation
{

	cat::middleware::dds::TransferData Read(
	    eprosima::fastdds::dds::rpc::RpcRequest const& info,
	    /*in*/ cat::middleware::dds::TransferData const& req
	) override
	{
		static_cast<void>(info);
		static_cast<void>(req);
		throw eprosima::fastdds::dds::rpc::RemoteUnsupportedError("Operation 'Read' is not implemented");
	}

	cat::middleware::dds::TransferData Write(
	    eprosima::fastdds::dds::rpc::RpcRequest const& info,
	    /*in*/ cat::middleware::dds::TransferData const& req
	) override
	{
		static_cast<void>(info);
		static_cast<void>(req);
		throw eprosima::fastdds::dds::rpc::RemoteUnsupportedError("Operation 'Write' is not implemented");
	}
};

//} interface Requests

}  // namespace dds

}  // namespace middleware

}  // namespace cat

#endif  // FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_SERVERIMPL_HPP
