// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file requests.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_HPP
#define FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/rpc/exceptions/RpcOperationError.hpp>
#include <fastdds/dds/rpc/interfaces/RpcFuture.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(REQUESTS_SOURCE)
#define REQUESTS_DllAPI __declspec(dllexport)
#else
#define REQUESTS_DllAPI __declspec(dllimport)
#endif  // REQUESTS_SOURCE
#else
#define REQUESTS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define REQUESTS_DllAPI
#endif  // _WIN32

namespace cat
{

namespace middleware
{

namespace dds
{

/*!
 * @brief This class represents the structure TransferData defined by the user in the IDL file.
 * @ingroup requests
 */
class TransferData
{
public:
	/*!
     * @brief Default constructor.
     */
	eProsima_user_DllExport TransferData()
	{
	}

	/*!
     * @brief Default destructor.
     */
	eProsima_user_DllExport ~TransferData()
	{
	}

	/*!
     * @brief Copy constructor.
     * @param x Reference to the object TransferData that will be copied.
     */
	eProsima_user_DllExport TransferData(TransferData const& x)
	{
		m_protobuf = x.m_protobuf;
	}

	/*!
     * @brief Move constructor.
     * @param x Reference to the object TransferData that will be copied.
     */
	eProsima_user_DllExport TransferData(TransferData&& x) noexcept
	{
		m_protobuf = std::move(x.m_protobuf);
	}

	/*!
     * @brief Copy assignment.
     * @param x Reference to the object TransferData that will be copied.
     */
	eProsima_user_DllExport TransferData& operator=(TransferData const& x)
	{

		m_protobuf = x.m_protobuf;

		return *this;
	}

	/*!
     * @brief Move assignment.
     * @param x Reference to the object TransferData that will be copied.
     */
	eProsima_user_DllExport TransferData& operator=(TransferData&& x) noexcept
	{

		m_protobuf = std::move(x.m_protobuf);
		return *this;
	}

	/*!
     * @brief Comparison operator.
     * @param x TransferData object to compare.
     */
	eProsima_user_DllExport bool operator==(TransferData const& x) const
	{
		return (m_protobuf == x.m_protobuf);
	}

	/*!
     * @brief Comparison operator.
     * @param x TransferData object to compare.
     */
	eProsima_user_DllExport bool operator!=(TransferData const& x) const
	{
		return !(*this == x);
	}

	/*!
     * @brief This function copies the value in member protobuf
     * @param _protobuf New value to be copied in member protobuf
     */
	eProsima_user_DllExport void protobuf(std::vector<uint8_t> const& _protobuf)
	{
		m_protobuf = _protobuf;
	}

	/*!
     * @brief This function moves the value in member protobuf
     * @param _protobuf New value to be moved in member protobuf
     */
	eProsima_user_DllExport void protobuf(std::vector<uint8_t>&& _protobuf)
	{
		m_protobuf = std::move(_protobuf);
	}

	/*!
     * @brief This function returns a constant reference to member protobuf
     * @return Constant reference to member protobuf
     */
	eProsima_user_DllExport const std::vector<uint8_t>& protobuf() const
	{
		return m_protobuf;
	}

	/*!
     * @brief This function returns a reference to member protobuf
     * @return Reference to member protobuf
     */
	eProsima_user_DllExport std::vector<uint8_t>& protobuf()
	{
		return m_protobuf;
	}

private:
	std::vector<uint8_t> m_protobuf;
};
/*!
 * @brief This class implements the user exception cat::middleware::dds::RequestException
 * @ingroup requests
 */
class eProsima_user_DllExport RequestException : public eprosima::fastdds::dds::rpc::RpcOperationError
{
public:
	/**
     * Default constructor.
     */
	RequestException() : RequestException("RequestException")
	{
	}

	/**
     * Constructor.
     */
	RequestException(std::string const& message) : eprosima::fastdds::dds::rpc::RpcOperationError(message)
	{
	}

	/**
     * Constructor.
     */
	RequestException(char const* message) : eprosima::fastdds::dds::rpc::RpcOperationError(message)
	{
	}

	/**
     * Copy constructor.
     */
	RequestException(RequestException const& other) noexcept = default;

	/**
     * Copy assignment.
     */
	RequestException& operator=(RequestException const& other) noexcept = default;

	/**
     * Destructor.
     */
	virtual ~RequestException() noexcept = default;

	/*!
     * @brief This function sets a value in member status_code
     * @param _status_code New value for member status_code
     */
	eProsima_user_DllExport void status_code(uint32_t _status_code)
	{
		m_status_code = _status_code;
	}

	/*!
     * @brief This function returns the value of member status_code
     * @return Value of member status_code
     */
	eProsima_user_DllExport uint32_t status_code() const
	{
		return m_status_code;
	}

	/*!
     * @brief This function returns a reference to member status_code
     * @return Reference to member status_code
     */
	eProsima_user_DllExport uint32_t& status_code()
	{
		return m_status_code;
	}

	/*!
     * @brief This function copies the value in member request
     * @param _request New value to be copied in member request
     */
	eProsima_user_DllExport void request(TransferData const& _request)
	{
		m_request = _request;
	}

	/*!
     * @brief This function moves the value in member request
     * @param _request New value to be moved in member request
     */
	eProsima_user_DllExport void request(TransferData&& _request)
	{
		m_request = std::move(_request);
	}

	/*!
     * @brief This function returns a constant reference to member request
     * @return Constant reference to member request
     */
	eProsima_user_DllExport const TransferData& request() const
	{
		return m_request;
	}

	/*!
     * @brief This function returns a reference to member request
     * @return Reference to member request
     */
	eProsima_user_DllExport TransferData& request()
	{
		return m_request;
	}

private:
	uint32_t m_status_code{0};
	TransferData m_request;
};

/*!
 * @brief This class represents the interface Requests defined by the user in the IDL file.
 * @ingroup requests
 */
class eProsima_user_DllExport Requests
{
public:
	virtual ~Requests() = default;

	virtual eprosima::fastdds::dds::rpc::RpcFuture<cat::middleware::dds::TransferData> Read(
	    /*in*/ cat::middleware::dds::TransferData const& req
	) = 0;

	virtual eprosima::fastdds::dds::rpc::RpcFuture<cat::middleware::dds::TransferData> Write(
	    /*in*/ cat::middleware::dds::TransferData const& req
	) = 0;
};

}  // namespace dds

}  // namespace middleware

}  // namespace cat

#endif  // _FAST_DDS_GENERATED_CAT_MIDDLEWARE_DDS_REQUESTS_HPP_
