// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file requests_details.hpp
 * This header file contains support data structures for RPC communication.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_DETAILS_HPP
#define FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_DETAILS_HPP

#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/rpc/RemoteExceptionCode_t.hpp>
#include <fastdds/dds/rpc/interfaces/RpcStatusCode.hpp>

#include "requests.hpp"

namespace cat
{
namespace middleware
{
namespace dds
{
namespace detail
{

//{ Requests interface

//{ Read
struct Requests_Read_In
{
	cat::middleware::dds::TransferData req;
};

struct Requests_Read_Out
{
	cat::middleware::dds::TransferData return_;
};

struct Requests_Read_Result
{
	eprosima::fastcdr::optional<cat::middleware::dds::detail::Requests_Read_Out> result;
	eprosima::fastcdr::optional<cat::middleware::dds::RequestException> cat_middleware_dds_RequestException_ex;
};

//}  // Read

//{ Write
struct Requests_Write_In
{
	cat::middleware::dds::TransferData req;
};

struct Requests_Write_Out
{
	cat::middleware::dds::TransferData return_;
};

struct Requests_Write_Result
{
	eprosima::fastcdr::optional<cat::middleware::dds::detail::Requests_Write_Out> result;
	eprosima::fastcdr::optional<cat::middleware::dds::RequestException> cat_middleware_dds_RequestException_ex;
};

//}  // Write

//{ top level

struct Requests_Request
{
	eprosima::fastcdr::optional<cat::middleware::dds::detail::Requests_Read_In> Read;
	eprosima::fastcdr::optional<cat::middleware::dds::detail::Requests_Write_In> Write;
};

struct Requests_Reply
{
	eprosima::fastcdr::optional<cat::middleware::dds::detail::Requests_Read_Result> Read;
	eprosima::fastcdr::optional<cat::middleware::dds::detail::Requests_Write_Result> Write;
	eprosima::fastcdr::optional<eprosima::fastdds::dds::rpc::RemoteExceptionCode_t> remoteEx;
};

//}  // top level

//}  // Requests interface

}  // namespace detail
}  // namespace dds
}  // namespace middleware
}  // namespace cat

#endif  //FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_DETAILS_HPP
