// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file requestsServer.hpp
 * Server implementation for interfaces
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_SERVER_HPP
#define FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_SERVER_HPP

#include <memory>

#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/domain/qos/ReplierQos.hpp>
#include <fastdds/dds/rpc/exceptions.hpp>
#include <fastdds/dds/rpc/interfaces.hpp>
#include <fastdds/rtps/common/Guid.hpp>
#include <fastdds/rtps/common/RemoteLocators.hpp>

#include "requests.hpp"

namespace cat
{

namespace middleware
{

namespace dds
{

struct RequestsServer_IServerImplementation
{
	virtual ~RequestsServer_IServerImplementation() = default;

	virtual cat::middleware::dds::TransferData Read(
	    eprosima::fastdds::dds::rpc::RpcRequest const& info,
	    /*in*/ cat::middleware::dds::TransferData const& req
	) = 0;

	virtual cat::middleware::dds::TransferData Write(
	    eprosima::fastdds::dds::rpc::RpcRequest const& info,
	    /*in*/ cat::middleware::dds::TransferData const& req
	) = 0;
};

/**
 * @brief Create a Requests server instance.
 *
 * @param part             The DomainParticipant to use for the server.
 * @param service_name     The name of the service.
 * @param qos              The QoS settings for the server.
 * @param thread_pool_size The size of the thread pool to use for processing requests.
 *                         When set to 0, a pool with a single thread will be created.
 * @param implementation   The implementation of the server interface.
 */
extern eProsima_user_DllExport std::shared_ptr<eprosima::fastdds::dds::rpc::RpcServer> create_RequestsServer(
    eprosima::fastdds::dds::DomainParticipant& part,
    char const* service_name,
    eprosima::fastdds::dds::ReplierQos const& qos,
    size_t thread_pool_size,
    std::shared_ptr<RequestsServer_IServerImplementation> implementation
);

/**
 * @brief Create a Requests server instance.
 *
 * @param part            The DomainParticipant to use for the server.
 * @param service_name    The name of the service.
 * @param qos             The QoS settings for the server.
 * @param scheduler       The request scheduling strategy to use for the server.
 * @param implementation  The implementation of the server interface.
 */
extern eProsima_user_DllExport std::shared_ptr<eprosima::fastdds::dds::rpc::RpcServer> create_RequestsServer(
    eprosima::fastdds::dds::DomainParticipant& part,
    char const* service_name,
    eprosima::fastdds::dds::ReplierQos const& qos,
    std::shared_ptr<eprosima::fastdds::dds::rpc::RpcServerSchedulingStrategy> scheduler,
    std::shared_ptr<RequestsServer_IServerImplementation> implementation
);

}  // namespace dds

}  // namespace middleware

}  // namespace cat

#endif  // FAST_DDS_GENERATED__CAT_MIDDLEWARE_DDS_REQUESTS_CLIENT_HPP
