// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file requestsPubSubTypes.cpp
 * This header file contains the implementation of the serialization functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "requestsPubSubTypes.hpp"

#include <fastdds/dds/log/Log.hpp>
#include <fastdds/rtps/common/CdrSerialization.hpp>

#include "requestsCdrAux.hpp"
#include "requestsTypeObjectSupport.hpp"

using SerializedPayload_t    = eprosima::fastdds::rtps::SerializedPayload_t;
using InstanceHandle_t       = eprosima::fastdds::rtps::InstanceHandle_t;
using DataRepresentationId_t = eprosima::fastdds::dds::DataRepresentationId_t;

namespace cat
{
namespace middleware
{
namespace dds
{
TransferDataPubSubType::TransferDataPubSubType()
{
	set_name("cat::middleware::dds::TransferData");
	uint32_t type_size = cat_middleware_dds_TransferData_max_cdr_typesize;
	type_size +=
	    static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
	max_serialized_type_size = type_size + 4;                                   /*encapsulation*/
	is_compute_key_provided  = false;
	uint32_t key_length      = cat_middleware_dds_TransferData_max_key_cdr_typesize > 16
	                               ? cat_middleware_dds_TransferData_max_key_cdr_typesize
	                               : 16;
	key_buffer_              = reinterpret_cast<unsigned char*>(malloc(key_length));
	memset(key_buffer_, 0, key_length);
}

TransferDataPubSubType::~TransferDataPubSubType()
{
	if(key_buffer_ != nullptr)
	{
		free(key_buffer_);
	}
}

bool TransferDataPubSubType::serialize(
    void const* const data,
    SerializedPayload_t& payload,
    DataRepresentationId_t data_representation
)
{
	::cat::middleware::dds::TransferData const* p_type = static_cast<::cat::middleware::dds::TransferData const*>(data);

	// Object that manages the raw buffer.
	eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
	// Object that serializes the data.
	eprosima::fastcdr::Cdr ser(
	    fastbuffer,
	    eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
	    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ? eprosima::fastcdr::CdrVersion::XCDRv1
	                                                                            : eprosima::fastcdr::CdrVersion::XCDRv2
	);
	payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
	ser.set_encoding_flag(
	    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION
	        ? eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR
	        : eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2
	);

	try
	{
		// Serialize encapsulation
		ser.serialize_encapsulation();
		// Serialize the object.
		ser << *p_type;
		ser.set_dds_cdr_options({0, 0});
	}
	catch(eprosima::fastcdr::exception::Exception& /*exception*/)
	{
		return false;
	}

	// Get the serialized length
	payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
	return true;
}

bool TransferDataPubSubType::deserialize(SerializedPayload_t& payload, void* data)
{
	try
	{
		// Convert DATA to pointer of your type
		::cat::middleware::dds::TransferData* p_type = static_cast<::cat::middleware::dds::TransferData*>(data);

		// Object that manages the raw buffer.
		eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

		// Object that deserializes the data.
		eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

		// Deserialize encapsulation.
		deser.read_encapsulation();
		payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

		// Deserialize the object.
		deser >> *p_type;
	}
	catch(eprosima::fastcdr::exception::Exception& /*exception*/)
	{
		return false;
	}

	return true;
}

uint32_t
TransferDataPubSubType::calculate_serialized_size(void const* const data, DataRepresentationId_t data_representation)
{
	try
	{
		eprosima::fastcdr::CdrSizeCalculator calculator(
		    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION
		        ? eprosima::fastcdr::CdrVersion::XCDRv1
		        : eprosima::fastcdr::CdrVersion::XCDRv2
		);
		size_t current_alignment{0};
		return static_cast<uint32_t>(calculator.calculate_serialized_size(
		           *static_cast<::cat::middleware::dds::TransferData const*>(data), current_alignment
		       )) +
		       4u /*encapsulation*/;
	}
	catch(eprosima::fastcdr::exception::Exception& /*exception*/)
	{
		return 0;
	}
}

void* TransferDataPubSubType::create_data()
{
	return reinterpret_cast<void*>(new ::cat::middleware::dds::TransferData());
}

void TransferDataPubSubType::delete_data(void* data)
{
	delete(reinterpret_cast<::cat::middleware::dds::TransferData*>(data));
}

bool TransferDataPubSubType::compute_key(SerializedPayload_t& payload, InstanceHandle_t& handle, bool force_md5)
{
	if(!is_compute_key_provided)
	{
		return false;
	}

	::cat::middleware::dds::TransferData data;
	if(deserialize(payload, static_cast<void*>(&data)))
	{
		return compute_key(static_cast<void*>(&data), handle, force_md5);
	}

	return false;
}

bool TransferDataPubSubType::compute_key(void const* const data, InstanceHandle_t& handle, bool force_md5)
{
	if(!is_compute_key_provided)
	{
		return false;
	}

	::cat::middleware::dds::TransferData const* p_type = static_cast<::cat::middleware::dds::TransferData const*>(data);

	// Object that manages the raw buffer.
	eprosima::fastcdr::FastBuffer fastbuffer(
	    reinterpret_cast<char*>(key_buffer_), cat_middleware_dds_TransferData_max_key_cdr_typesize
	);

	// Object that serializes the data.
	eprosima::fastcdr::Cdr ser(
	    fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2
	);
	ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
	eprosima::fastcdr::serialize_key(ser, *p_type);
	if(force_md5 || cat_middleware_dds_TransferData_max_key_cdr_typesize > 16)
	{
		md5_.init();
		md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
		md5_.finalize();
		for(uint8_t i = 0; i < 16; ++i)
		{
			handle.value[i] = md5_.digest[i];
		}
	}
	else
	{
		for(uint8_t i = 0; i < 16; ++i)
		{
			handle.value[i] = key_buffer_[i];
		}
	}
	return true;
}

void TransferDataPubSubType::register_type_object_representation()
{
	register_TransferData_type_identifier(type_identifiers_);
}

// { Requests interface

class Requests_RequestPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:
	// Alias for the type to be serialized.
	typedef detail::Requests_Request type;

	// Constructor
	Requests_RequestPubSubType()
	{
		set_name("cat::middleware::dds::Requests_Request");
		uint32_t type_size = 44UL;
		type_size +=
		    static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
		max_serialized_type_size = type_size + 4;                                   /*encapsulation*/
		is_compute_key_provided  = false;
	}

	// Destructor
	~Requests_RequestPubSubType() override = default;

	// This function serializes the data.
	eProsima_user_DllExport bool serialize(
	    void const* const data,
	    eprosima::fastdds::rtps::SerializedPayload_t& payload,
	    eprosima::fastdds::dds::DataRepresentationId_t data_representation
	) override
	{
		type const* p_type = static_cast<type const*>(data);

		// Object that manages the raw buffer.
		eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
		// Object that serializes the data.
		eprosima::fastcdr::Cdr ser(
		    fastbuffer,
		    eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
		    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION
		        ? eprosima::fastcdr::CdrVersion::XCDRv1
		        : eprosima::fastcdr::CdrVersion::XCDRv2
		);
		payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
		ser.set_encoding_flag(
		    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION
		        ? eprosima::fastcdr::EncodingAlgorithmFlag::PL_CDR
		        : eprosima::fastcdr::EncodingAlgorithmFlag::PL_CDR2
		);

		try
		{
			// Serialize encapsulation
			ser.serialize_encapsulation();
			// Serialize the object.
			ser << *p_type;
			ser.set_dds_cdr_options({0, 0});
		}
		catch(eprosima::fastcdr::exception::Exception& /*exception*/)
		{
			return false;
		}

		// Get the serialized length
		payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
		return true;
	}

	eProsima_user_DllExport bool deserialize(eprosima::fastdds::rtps::SerializedPayload_t& payload, void* data) override
	{
		try
		{
			// Convert DATA to pointer of your type
			type* p_type = static_cast<type*>(data);

			// Object that manages the raw buffer.
			eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

			// Object that deserializes the data.
			eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

			// Deserialize encapsulation.
			deser.read_encapsulation();
			payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

			// Deserialize the object.
			deser >> *p_type;
		}
		catch(eprosima::fastcdr::exception::Exception& /*exception*/)
		{
			return false;
		}

		return true;
	}

	eProsima_user_DllExport uint32_t calculate_serialized_size(
	    void const* const data,
	    eprosima::fastdds::dds::DataRepresentationId_t data_representation
	) override
	{
		try
		{
			eprosima::fastcdr::CdrSizeCalculator calculator(
			    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION
			        ? eprosima::fastcdr::CdrVersion::XCDRv1
			        : eprosima::fastcdr::CdrVersion::XCDRv2
			);
			size_t current_alignment{0};
			return static_cast<uint32_t>(
			           calculator.calculate_serialized_size(*static_cast<type const*>(data), current_alignment)
			       ) +
			       4u /*encapsulation*/;
		}
		catch(eprosima::fastcdr::exception::Exception& /*exception*/)
		{
			return 0;
		}
	}

	eProsima_user_DllExport bool compute_key(
	    eprosima::fastdds::rtps::SerializedPayload_t& payload,
	    eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
	    bool force_md5 = false
	) override
	{
		static_cast<void>(payload);
		static_cast<void>(ihandle);
		static_cast<void>(force_md5);
		return false;
	}

	eProsima_user_DllExport bool compute_key(
	    void const* const data,
	    eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
	    bool force_md5 = false
	) override
	{
		static_cast<void>(data);
		static_cast<void>(ihandle);
		static_cast<void>(force_md5);
		return false;
	}

	eProsima_user_DllExport void* create_data() override
	{
		return new type();
	}

	eProsima_user_DllExport void delete_data(void* data) override
	{
		type* pData = static_cast<type*>(data);
		delete pData;
	}

	eProsima_user_DllExport void register_type_object_representation() override
	{
		register_Requests_Request_type_identifier(type_identifiers_);
	}
};

class Requests_ReplyPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:
	// Alias for the type to be serialized.
	typedef detail::Requests_Reply type;

	// Constructor
	Requests_ReplyPubSubType()
	{
		set_name("cat::middleware::dds::Requests_Reply");
		uint32_t type_size = 44UL;
		type_size +=
		    static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
		max_serialized_type_size = type_size + 4;                                   /*encapsulation*/
		is_compute_key_provided  = false;
	}

	// Destructor
	~Requests_ReplyPubSubType() override = default;

	// This function serializes the data.
	eProsima_user_DllExport bool serialize(
	    void const* const data,
	    eprosima::fastdds::rtps::SerializedPayload_t& payload,
	    eprosima::fastdds::dds::DataRepresentationId_t data_representation
	) override
	{
		type const* p_type = static_cast<type const*>(data);

		// Object that manages the raw buffer.
		eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
		// Object that serializes the data.
		eprosima::fastcdr::Cdr ser(
		    fastbuffer,
		    eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
		    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION
		        ? eprosima::fastcdr::CdrVersion::XCDRv1
		        : eprosima::fastcdr::CdrVersion::XCDRv2
		);
		payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
		ser.set_encoding_flag(
		    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION
		        ? eprosima::fastcdr::EncodingAlgorithmFlag::PL_CDR
		        : eprosima::fastcdr::EncodingAlgorithmFlag::PL_CDR2
		);

		try
		{
			// Serialize encapsulation
			ser.serialize_encapsulation();
			// Serialize the object.
			ser << *p_type;
			ser.set_dds_cdr_options({0, 0});
		}
		catch(eprosima::fastcdr::exception::Exception& /*exception*/)
		{
			return false;
		}

		// Get the serialized length
		payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
		return true;
	}

	eProsima_user_DllExport bool deserialize(eprosima::fastdds::rtps::SerializedPayload_t& payload, void* data) override
	{
		try
		{
			// Convert DATA to pointer of your type
			type* p_type = static_cast<type*>(data);

			// Object that manages the raw buffer.
			eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

			// Object that deserializes the data.
			eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

			// Deserialize encapsulation.
			deser.read_encapsulation();
			payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

			// Deserialize the object.
			deser >> *p_type;
		}
		catch(eprosima::fastcdr::exception::Exception& /*exception*/)
		{
			return false;
		}

		return true;
	}

	eProsima_user_DllExport uint32_t calculate_serialized_size(
	    void const* const data,
	    eprosima::fastdds::dds::DataRepresentationId_t data_representation
	) override
	{
		try
		{
			eprosima::fastcdr::CdrSizeCalculator calculator(
			    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION
			        ? eprosima::fastcdr::CdrVersion::XCDRv1
			        : eprosima::fastcdr::CdrVersion::XCDRv2
			);
			size_t current_alignment{0};
			return static_cast<uint32_t>(
			           calculator.calculate_serialized_size(*static_cast<type const*>(data), current_alignment)
			       ) +
			       4u /*encapsulation*/;
		}
		catch(eprosima::fastcdr::exception::Exception& /*exception*/)
		{
			return 0;
		}
	}

	eProsima_user_DllExport bool compute_key(
	    eprosima::fastdds::rtps::SerializedPayload_t& payload,
	    eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
	    bool force_md5 = false
	) override
	{
		static_cast<void>(payload);
		static_cast<void>(ihandle);
		static_cast<void>(force_md5);
		return false;
	}

	eProsima_user_DllExport bool compute_key(
	    void const* const data,
	    eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
	    bool force_md5 = false
	) override
	{
		static_cast<void>(data);
		static_cast<void>(ihandle);
		static_cast<void>(force_md5);
		return false;
	}

	eProsima_user_DllExport void* create_data() override
	{
		return new type();
	}

	eProsima_user_DllExport void delete_data(void* data) override
	{
		type* pData = static_cast<type*>(data);
		delete pData;
	}

	eProsima_user_DllExport void register_type_object_representation() override
	{
		register_Requests_Reply_type_identifier(type_identifiers_);
	}
};

eprosima::fastdds::dds::rpc::ServiceTypeSupport create_Requests_service_type_support()
{
	eprosima::fastdds::dds::TypeSupport request_type(new Requests_RequestPubSubType());
	eprosima::fastdds::dds::TypeSupport reply_type(new Requests_ReplyPubSubType());
	return eprosima::fastdds::dds::rpc::ServiceTypeSupport(request_type, reply_type);
}

// }  // Requests interface

}  // namespace dds

}  // namespace middleware

}  // namespace cat

// Include auxiliary functions like for serializing/deserializing.
#include "requestsCdrAux.ipp"
