// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file requestsTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "requestsTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/rpc/RPCTypeObjectSupport.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "requests.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace cat
{
namespace middleware
{
namespace dds
{
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_TransferData_type_identifier(TypeIdentifierPair& type_ids_TransferData)
{

	ReturnCode_t return_code_TransferData{eprosima::fastdds::dds::RETCODE_OK};
	return_code_TransferData =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::dds::TransferData", type_ids_TransferData
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_TransferData)
	{
		StructTypeFlag struct_flags_TransferData = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE, false, false
		);
		QualifiedTypeName type_name_TransferData = "cat::middleware::dds::TransferData";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_TransferData;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_TransferData;
		CompleteTypeDetail detail_TransferData = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_TransferData, ann_custom_TransferData, type_name_TransferData.to_string()
		);
		CompleteStructHeader header_TransferData;
		header_TransferData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_TransferData);
		CompleteStructMemberSeq member_seq_TransferData;
		{
			TypeIdentifierPair type_ids_protobuf;
			ReturnCode_t return_code_protobuf{eprosima::fastdds::dds::RETCODE_OK};
			return_code_protobuf = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			                           ->type_object_registry()
			                           .get_type_identifiers("anonymous_sequence_byte_unbounded", type_ids_protobuf);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_protobuf)
			{
				return_code_protobuf = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
				                           ->type_object_registry()
				                           .get_type_identifiers("_byte", type_ids_protobuf);

				if(eprosima::fastdds::dds::RETCODE_OK != return_code_protobuf)
				{
					EPROSIMA_LOG_ERROR(
					    XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier unknown to TypeObjectRegistry."
					);
					return;
				}
				bool element_identifier_anonymous_sequence_byte_unbounded_ec{false};
				TypeIdentifier* element_identifier_anonymous_sequence_byte_unbounded{new TypeIdentifier(
				    TypeObjectUtils::retrieve_complete_type_identifier(
				        type_ids_protobuf, element_identifier_anonymous_sequence_byte_unbounded_ec
				    )
				)};
				if(!element_identifier_anonymous_sequence_byte_unbounded_ec)
				{
					EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
					return;
				}
				EquivalenceKind equiv_kind_anonymous_sequence_byte_unbounded = EK_COMPLETE;
				if(TK_NONE == type_ids_protobuf.type_identifier2()._d())
				{
					equiv_kind_anonymous_sequence_byte_unbounded = EK_BOTH;
				}
				CollectionElementFlag element_flags_anonymous_sequence_byte_unbounded = 0;
				PlainCollectionHeader header_anonymous_sequence_byte_unbounded =
				    TypeObjectUtils::build_plain_collection_header(
				        equiv_kind_anonymous_sequence_byte_unbounded, element_flags_anonymous_sequence_byte_unbounded
				    );
				{
					SBound bound                     = 0;
					PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(
					    header_anonymous_sequence_byte_unbounded,
					    bound,
					    eprosima::fastcdr::external<TypeIdentifier>(
					        element_identifier_anonymous_sequence_byte_unbounded
					    )
					);
					if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
					   TypeObjectUtils::build_and_register_s_sequence_type_identifier(
					       seq_sdefn, "anonymous_sequence_byte_unbounded", type_ids_protobuf
					   ))
					{
						EPROSIMA_LOG_ERROR(
						    XTYPES_TYPE_REPRESENTATION,
						    "anonymous_sequence_byte_unbounded already registered in TypeObjectRegistry for a "
						    "different type."
						);
					}
				}
			}
			StructMemberFlag member_flags_protobuf = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false
			);
			MemberId member_id_protobuf = 0x00000000;
			bool common_protobuf_ec{false};
			CommonStructMember common_protobuf{TypeObjectUtils::build_common_struct_member(
			    member_id_protobuf,
			    member_flags_protobuf,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_protobuf, common_protobuf_ec)
			)};
			if(!common_protobuf_ec)
			{
				EPROSIMA_LOG_ERROR(
				    XTYPES_TYPE_REPRESENTATION, "Structure protobuf member TypeIdentifier inconsistent."
				);
				return;
			}
			MemberName name_protobuf = "protobuf";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_protobuf;
			ann_custom_TransferData.reset();
			CompleteMemberDetail detail_protobuf = TypeObjectUtils::build_complete_member_detail(
			    name_protobuf, member_ann_builtin_protobuf, ann_custom_TransferData
			);
			CompleteStructMember member_protobuf =
			    TypeObjectUtils::build_complete_struct_member(common_protobuf, detail_protobuf);
			TypeObjectUtils::add_complete_struct_member(member_seq_TransferData, member_protobuf);
		}
		CompleteStructType struct_type_TransferData = TypeObjectUtils::build_complete_struct_type(
		    struct_flags_TransferData, header_TransferData, member_seq_TransferData
		);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
		   TypeObjectUtils::build_and_register_struct_type_object(
		       struct_type_TransferData, type_name_TransferData.to_string(), type_ids_TransferData
		   ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::TransferData already registered in TypeObjectRegistry for a different type."
			);
		}
	}
}  // TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_RequestException_type_identifier(TypeIdentifierPair& type_ids_RequestException)
{

	ReturnCode_t return_code_RequestException{eprosima::fastdds::dds::RETCODE_OK};
	return_code_RequestException =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::dds::RequestException", type_ids_RequestException
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_RequestException)
	{
		StructTypeFlag struct_flags_RequestException = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL, false, false
		);
		return_code_RequestException =
		    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
		        ->type_object_registry()
		        .get_type_identifiers("eprosima::fastdds::dds::rpc::RpcOperationError", type_ids_RequestException);

		if(return_code_RequestException != eprosima::fastdds::dds::RETCODE_OK)
		{
			::eprosima::fastdds::dds::rpc::register_RpcOperationError_type_identifier(type_ids_RequestException);
		}
		QualifiedTypeName type_name_RequestException = "cat::middleware::dds::RequestException";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_RequestException;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_RequestException;
		CompleteTypeDetail detail_RequestException = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_RequestException, ann_custom_RequestException, type_name_RequestException.to_string()
		);
		CompleteStructHeader header_RequestException;
		if(EK_COMPLETE == type_ids_RequestException.type_identifier1()._d())
		{
			header_RequestException = TypeObjectUtils::build_complete_struct_header(
			    type_ids_RequestException.type_identifier1(), detail_RequestException
			);
		}
		else if(EK_COMPLETE == type_ids_RequestException.type_identifier2()._d())
		{
			header_RequestException = TypeObjectUtils::build_complete_struct_header(
			    type_ids_RequestException.type_identifier2(), detail_RequestException
			);
		}
		else
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::RequestException Structure: base_type TypeIdentifier registered in "
			    "TypeObjectRegistry is inconsistent."
			);
			return;
		}
		CompleteStructMemberSeq member_seq_RequestException;
		{
			TypeIdentifierPair type_ids_status_code;
			ReturnCode_t return_code_status_code{eprosima::fastdds::dds::RETCODE_OK};
			return_code_status_code = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			                              ->type_object_registry()
			                              .get_type_identifiers("_uint32_t", type_ids_status_code);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_status_code)
			{
				EPROSIMA_LOG_ERROR(
				    XTYPES_TYPE_REPRESENTATION,
				    "status_code Structure member TypeIdentifier unknown to TypeObjectRegistry."
				);
				return;
			}
			StructMemberFlag member_flags_status_code = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false
			);
			MemberId member_id_status_code = 0x00000001;
			bool common_status_code_ec{false};
			CommonStructMember common_status_code{TypeObjectUtils::build_common_struct_member(
			    member_id_status_code,
			    member_flags_status_code,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_status_code, common_status_code_ec)
			)};
			if(!common_status_code_ec)
			{
				EPROSIMA_LOG_ERROR(
				    XTYPES_TYPE_REPRESENTATION, "Structure status_code member TypeIdentifier inconsistent."
				);
				return;
			}
			MemberName name_status_code = "status_code";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_status_code;
			ann_custom_RequestException.reset();
			CompleteMemberDetail detail_status_code = TypeObjectUtils::build_complete_member_detail(
			    name_status_code, member_ann_builtin_status_code, ann_custom_RequestException
			);
			CompleteStructMember member_status_code =
			    TypeObjectUtils::build_complete_struct_member(common_status_code, detail_status_code);
			TypeObjectUtils::add_complete_struct_member(member_seq_RequestException, member_status_code);
		}
		{
			TypeIdentifierPair type_ids_request;
			ReturnCode_t return_code_request{eprosima::fastdds::dds::RETCODE_OK};
			return_code_request = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			                          ->type_object_registry()
			                          .get_type_identifiers("cat::middleware::dds::TransferData", type_ids_request);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_request)
			{
				::cat::middleware::dds::register_TransferData_type_identifier(type_ids_request);
			}
			StructMemberFlag member_flags_request = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false
			);
			MemberId member_id_request = 0x00000002;
			bool common_request_ec{false};
			CommonStructMember common_request{TypeObjectUtils::build_common_struct_member(
			    member_id_request,
			    member_flags_request,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_request, common_request_ec)
			)};
			if(!common_request_ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure request member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_request = "request";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_request;
			ann_custom_RequestException.reset();
			CompleteMemberDetail detail_request = TypeObjectUtils::build_complete_member_detail(
			    name_request, member_ann_builtin_request, ann_custom_RequestException
			);
			CompleteStructMember member_request =
			    TypeObjectUtils::build_complete_struct_member(common_request, detail_request);
			TypeObjectUtils::add_complete_struct_member(member_seq_RequestException, member_request);
		}
		CompleteStructType struct_type_RequestException = TypeObjectUtils::build_complete_struct_type(
		    struct_flags_RequestException, header_RequestException, member_seq_RequestException
		);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
		   TypeObjectUtils::build_and_register_struct_type_object(
		       struct_type_RequestException, type_name_RequestException.to_string(), type_ids_RequestException
		   ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::RequestException already registered in TypeObjectRegistry for a different type."
			);
		}
	}
}

namespace detail
{

//{ Read
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Requests_Read_In_type_identifier(TypeIdentifierPair& type_ids_Requests_Read_In)
{

	ReturnCode_t return_code_Requests_Read_In{eprosima::fastdds::dds::RETCODE_OK};
	return_code_Requests_Read_In =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::dds::detail::Requests_Read_In", type_ids_Requests_Read_In
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_Requests_Read_In)
	{
		StructTypeFlag struct_flags_Requests_Read_In = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL, false, false
		);
		QualifiedTypeName type_name_Requests_Read_In = "cat::middleware::dds::detail::Requests_Read_In";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Requests_Read_In;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Requests_Read_In;
		CompleteTypeDetail detail_Requests_Read_In = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_Requests_Read_In, ann_custom_Requests_Read_In, type_name_Requests_Read_In.to_string()
		);
		CompleteStructHeader header_Requests_Read_In;
		header_Requests_Read_In =
		    TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Requests_Read_In);
		CompleteStructMemberSeq member_seq_Requests_Read_In;
		{
			TypeIdentifierPair type_ids_req;
			ReturnCode_t return_code_req{eprosima::fastdds::dds::RETCODE_OK};
			return_code_req = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			                      ->type_object_registry()
			                      .get_type_identifiers("cat::middleware::dds::TransferData", type_ids_req);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_req)
			{
				::cat::middleware::dds::register_TransferData_type_identifier(type_ids_req);
			}
			StructMemberFlag member_flags_req = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false
			);
			MemberId member_id_req = 0x00000000;
			bool common_req_ec{false};
			CommonStructMember common_req{TypeObjectUtils::build_common_struct_member(
			    member_id_req,
			    member_flags_req,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_req, common_req_ec)
			)};
			if(!common_req_ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure req member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_req = "req";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_req;
			ann_custom_Requests_Read_In.reset();
			CompleteMemberDetail detail_req = TypeObjectUtils::build_complete_member_detail(
			    name_req, member_ann_builtin_req, ann_custom_Requests_Read_In
			);
			CompleteStructMember member_req = TypeObjectUtils::build_complete_struct_member(common_req, detail_req);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Read_In, member_req);
		}
		CompleteStructType struct_type_Requests_Read_In = TypeObjectUtils::build_complete_struct_type(
		    struct_flags_Requests_Read_In, header_Requests_Read_In, member_seq_Requests_Read_In
		);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
		   TypeObjectUtils::build_and_register_struct_type_object(
		       struct_type_Requests_Read_In, type_name_Requests_Read_In.to_string(), type_ids_Requests_Read_In
		   ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::detail::Requests_Read_In already registered in TypeObjectRegistry for a "
			    "different type."
			);
		}
	}
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Requests_Read_Out_type_identifier(TypeIdentifierPair& type_ids_Requests_Read_Out)
{

	ReturnCode_t return_code_Requests_Read_Out{eprosima::fastdds::dds::RETCODE_OK};
	return_code_Requests_Read_Out =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::dds::detail::Requests_Read_Out", type_ids_Requests_Read_Out
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_Requests_Read_Out)
	{
		StructTypeFlag struct_flags_Requests_Read_Out = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL, false, false
		);
		QualifiedTypeName type_name_Requests_Read_Out = "cat::middleware::dds::detail::Requests_Read_Out";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Requests_Read_Out;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Requests_Read_Out;
		CompleteTypeDetail detail_Requests_Read_Out = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_Requests_Read_Out, ann_custom_Requests_Read_Out, type_name_Requests_Read_Out.to_string()
		);
		CompleteStructHeader header_Requests_Read_Out;
		header_Requests_Read_Out =
		    TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Requests_Read_Out);
		CompleteStructMemberSeq member_seq_Requests_Read_Out;
		{
			TypeIdentifierPair type_ids_return_;
			ReturnCode_t return_code_return_{eprosima::fastdds::dds::RETCODE_OK};
			return_code_return_ = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			                          ->type_object_registry()
			                          .get_type_identifiers("cat::middleware::dds::TransferData", type_ids_return_);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_return_)
			{
				::cat::middleware::dds::register_TransferData_type_identifier(type_ids_return_);
			}
			StructMemberFlag member_flags_return_ = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false
			);
			MemberId member_id_return_ = 0x00000000;
			bool common_return__ec{false};
			CommonStructMember common_return_{TypeObjectUtils::build_common_struct_member(
			    member_id_return_,
			    member_flags_return_,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_return_, common_return__ec)
			)};
			if(!common_return__ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure return_ member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_return_ = "return_";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_return_;
			ann_custom_Requests_Read_Out.reset();
			CompleteMemberDetail detail_return_ = TypeObjectUtils::build_complete_member_detail(
			    name_return_, member_ann_builtin_return_, ann_custom_Requests_Read_Out
			);
			CompleteStructMember member_return_ =
			    TypeObjectUtils::build_complete_struct_member(common_return_, detail_return_);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Read_Out, member_return_);
		}
		CompleteStructType struct_type_Requests_Read_Out = TypeObjectUtils::build_complete_struct_type(
		    struct_flags_Requests_Read_Out, header_Requests_Read_Out, member_seq_Requests_Read_Out
		);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
		   TypeObjectUtils::build_and_register_struct_type_object(
		       struct_type_Requests_Read_Out, type_name_Requests_Read_Out.to_string(), type_ids_Requests_Read_Out
		   ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::detail::Requests_Read_Out already registered in TypeObjectRegistry for a "
			    "different type."
			);
		}
	}
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Requests_Read_Result_type_identifier(TypeIdentifierPair& type_ids_Requests_Read_Result)
{

	ReturnCode_t return_code_Requests_Read_Result{eprosima::fastdds::dds::RETCODE_OK};
	return_code_Requests_Read_Result =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::dds::detail::Requests_Read_Result", type_ids_Requests_Read_Result
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_Requests_Read_Result)
	{
		StructTypeFlag struct_flags_Requests_Read_Result = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::MUTABLE, false, false
		);
		QualifiedTypeName type_name_Requests_Read_Result = "cat::middleware::dds::detail::Requests_Read_Result";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Requests_Read_Result;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Requests_Read_Result;
		CompleteTypeDetail detail_Requests_Read_Result = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_Requests_Read_Result,
		    ann_custom_Requests_Read_Result,
		    type_name_Requests_Read_Result.to_string()
		);
		CompleteStructHeader header_Requests_Read_Result;
		header_Requests_Read_Result =
		    TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Requests_Read_Result);
		CompleteStructMemberSeq member_seq_Requests_Read_Result;
		{
			TypeIdentifierPair type_ids_result;
			ReturnCode_t return_code_result{eprosima::fastdds::dds::RETCODE_OK};
			return_code_result =
			    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			        ->type_object_registry()
			        .get_type_identifiers("cat::middleware::dds::detail::Requests_Read_Out", type_ids_result);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_result)
			{
				::cat::middleware::dds::detail::register_Requests_Read_Out_type_identifier(type_ids_result);
			}
			StructMemberFlag member_flags_result = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, true, false, false, false
			);
			MemberId member_id_result = 0x0784a8b4;
			bool common_result_ec{false};
			CommonStructMember common_result{TypeObjectUtils::build_common_struct_member(
			    member_id_result,
			    member_flags_result,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_result, common_result_ec)
			)};
			if(!common_result_ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure result member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_result = "result";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_result;
			ann_custom_Requests_Read_Result.reset();
			AppliedAnnotationSeq tmp_ann_custom_result;
			eprosima::fastcdr::optional<std::string> unit_result;
			eprosima::fastcdr::optional<AnnotationParameterValue> min_result;
			eprosima::fastcdr::optional<AnnotationParameterValue> max_result;
			eprosima::fastcdr::optional<std::string> hash_id_result;
			hash_id_result = "";

			if(unit_result.has_value() || min_result.has_value() || max_result.has_value() ||
			   hash_id_result.has_value())
			{
				member_ann_builtin_result = TypeObjectUtils::build_applied_builtin_member_annotations(
				    unit_result, min_result, max_result, hash_id_result
				);
			}
			if(!tmp_ann_custom_result.empty())
			{
				ann_custom_Requests_Read_Result = tmp_ann_custom_result;
			}
			CompleteMemberDetail detail_result = TypeObjectUtils::build_complete_member_detail(
			    name_result, member_ann_builtin_result, ann_custom_Requests_Read_Result
			);
			CompleteStructMember member_result =
			    TypeObjectUtils::build_complete_struct_member(common_result, detail_result);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Read_Result, member_result);
		}
		{
			TypeIdentifierPair type_ids_cat_middleware_dds_RequestException_ex;
			ReturnCode_t return_code_cat_middleware_dds_RequestException_ex{eprosima::fastdds::dds::RETCODE_OK};
			return_code_cat_middleware_dds_RequestException_ex =
			    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			        ->type_object_registry()
			        .get_type_identifiers(
			            "cat::middleware::dds::RequestException", type_ids_cat_middleware_dds_RequestException_ex
			        );

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_cat_middleware_dds_RequestException_ex)
			{
				::cat::middleware::dds::register_RequestException_type_identifier(
				    type_ids_cat_middleware_dds_RequestException_ex
				);
			}
			StructMemberFlag member_flags_cat_middleware_dds_RequestException_ex =
			    TypeObjectUtils::build_struct_member_flag(
			        eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, true, false, false, false
			    );
			MemberId member_id_cat_middleware_dds_RequestException_ex = 0x092eb941;
			bool common_cat_middleware_dds_RequestException_ex_ec{false};
			CommonStructMember common_cat_middleware_dds_RequestException_ex{
			    TypeObjectUtils::build_common_struct_member(
			        member_id_cat_middleware_dds_RequestException_ex,
			        member_flags_cat_middleware_dds_RequestException_ex,
			        TypeObjectUtils::retrieve_complete_type_identifier(
			            type_ids_cat_middleware_dds_RequestException_ex,
			            common_cat_middleware_dds_RequestException_ex_ec
			        )
			    )
			};
			if(!common_cat_middleware_dds_RequestException_ex_ec)
			{
				EPROSIMA_LOG_ERROR(
				    XTYPES_TYPE_REPRESENTATION,
				    "Structure cat_middleware_dds_RequestException_ex member TypeIdentifier inconsistent."
				);
				return;
			}
			MemberName name_cat_middleware_dds_RequestException_ex = "cat_middleware_dds_RequestException_ex";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations>
			    member_ann_builtin_cat_middleware_dds_RequestException_ex;
			ann_custom_Requests_Read_Result.reset();
			AppliedAnnotationSeq tmp_ann_custom_cat_middleware_dds_RequestException_ex;
			eprosima::fastcdr::optional<std::string> unit_cat_middleware_dds_RequestException_ex;
			eprosima::fastcdr::optional<AnnotationParameterValue> min_cat_middleware_dds_RequestException_ex;
			eprosima::fastcdr::optional<AnnotationParameterValue> max_cat_middleware_dds_RequestException_ex;
			eprosima::fastcdr::optional<std::string> hash_id_cat_middleware_dds_RequestException_ex;
			hash_id_cat_middleware_dds_RequestException_ex = "";

			if(unit_cat_middleware_dds_RequestException_ex.has_value() ||
			   min_cat_middleware_dds_RequestException_ex.has_value() ||
			   max_cat_middleware_dds_RequestException_ex.has_value() ||
			   hash_id_cat_middleware_dds_RequestException_ex.has_value())
			{
				member_ann_builtin_cat_middleware_dds_RequestException_ex =
				    TypeObjectUtils::build_applied_builtin_member_annotations(
				        unit_cat_middleware_dds_RequestException_ex,
				        min_cat_middleware_dds_RequestException_ex,
				        max_cat_middleware_dds_RequestException_ex,
				        hash_id_cat_middleware_dds_RequestException_ex
				    );
			}
			if(!tmp_ann_custom_cat_middleware_dds_RequestException_ex.empty())
			{
				ann_custom_Requests_Read_Result = tmp_ann_custom_cat_middleware_dds_RequestException_ex;
			}
			CompleteMemberDetail detail_cat_middleware_dds_RequestException_ex =
			    TypeObjectUtils::build_complete_member_detail(
			        name_cat_middleware_dds_RequestException_ex,
			        member_ann_builtin_cat_middleware_dds_RequestException_ex,
			        ann_custom_Requests_Read_Result
			    );
			CompleteStructMember member_cat_middleware_dds_RequestException_ex =
			    TypeObjectUtils::build_complete_struct_member(
			        common_cat_middleware_dds_RequestException_ex, detail_cat_middleware_dds_RequestException_ex
			    );
			TypeObjectUtils::add_complete_struct_member(
			    member_seq_Requests_Read_Result, member_cat_middleware_dds_RequestException_ex
			);
		}
		CompleteStructType struct_type_Requests_Read_Result = TypeObjectUtils::build_complete_struct_type(
		    struct_flags_Requests_Read_Result, header_Requests_Read_Result, member_seq_Requests_Read_Result
		);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER == TypeObjectUtils::build_and_register_struct_type_object(
		                                                        struct_type_Requests_Read_Result,
		                                                        type_name_Requests_Read_Result.to_string(),
		                                                        type_ids_Requests_Read_Result
		                                                    ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::detail::Requests_Read_Result already registered in TypeObjectRegistry for a "
			    "different type."
			);
		}
	}
}

//}  // Read

//{ Write
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Requests_Write_In_type_identifier(TypeIdentifierPair& type_ids_Requests_Write_In)
{

	ReturnCode_t return_code_Requests_Write_In{eprosima::fastdds::dds::RETCODE_OK};
	return_code_Requests_Write_In =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::dds::detail::Requests_Write_In", type_ids_Requests_Write_In
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_Requests_Write_In)
	{
		StructTypeFlag struct_flags_Requests_Write_In = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL, false, false
		);
		QualifiedTypeName type_name_Requests_Write_In = "cat::middleware::dds::detail::Requests_Write_In";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Requests_Write_In;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Requests_Write_In;
		CompleteTypeDetail detail_Requests_Write_In = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_Requests_Write_In, ann_custom_Requests_Write_In, type_name_Requests_Write_In.to_string()
		);
		CompleteStructHeader header_Requests_Write_In;
		header_Requests_Write_In =
		    TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Requests_Write_In);
		CompleteStructMemberSeq member_seq_Requests_Write_In;
		{
			TypeIdentifierPair type_ids_req;
			ReturnCode_t return_code_req{eprosima::fastdds::dds::RETCODE_OK};
			return_code_req = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			                      ->type_object_registry()
			                      .get_type_identifiers("cat::middleware::dds::TransferData", type_ids_req);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_req)
			{
				::cat::middleware::dds::register_TransferData_type_identifier(type_ids_req);
			}
			StructMemberFlag member_flags_req = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false
			);
			MemberId member_id_req = 0x00000000;
			bool common_req_ec{false};
			CommonStructMember common_req{TypeObjectUtils::build_common_struct_member(
			    member_id_req,
			    member_flags_req,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_req, common_req_ec)
			)};
			if(!common_req_ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure req member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_req = "req";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_req;
			ann_custom_Requests_Write_In.reset();
			CompleteMemberDetail detail_req = TypeObjectUtils::build_complete_member_detail(
			    name_req, member_ann_builtin_req, ann_custom_Requests_Write_In
			);
			CompleteStructMember member_req = TypeObjectUtils::build_complete_struct_member(common_req, detail_req);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Write_In, member_req);
		}
		CompleteStructType struct_type_Requests_Write_In = TypeObjectUtils::build_complete_struct_type(
		    struct_flags_Requests_Write_In, header_Requests_Write_In, member_seq_Requests_Write_In
		);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
		   TypeObjectUtils::build_and_register_struct_type_object(
		       struct_type_Requests_Write_In, type_name_Requests_Write_In.to_string(), type_ids_Requests_Write_In
		   ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::detail::Requests_Write_In already registered in TypeObjectRegistry for a "
			    "different type."
			);
		}
	}
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Requests_Write_Out_type_identifier(TypeIdentifierPair& type_ids_Requests_Write_Out)
{

	ReturnCode_t return_code_Requests_Write_Out{eprosima::fastdds::dds::RETCODE_OK};
	return_code_Requests_Write_Out =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::dds::detail::Requests_Write_Out", type_ids_Requests_Write_Out
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_Requests_Write_Out)
	{
		StructTypeFlag struct_flags_Requests_Write_Out = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL, false, false
		);
		QualifiedTypeName type_name_Requests_Write_Out = "cat::middleware::dds::detail::Requests_Write_Out";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Requests_Write_Out;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Requests_Write_Out;
		CompleteTypeDetail detail_Requests_Write_Out = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_Requests_Write_Out, ann_custom_Requests_Write_Out, type_name_Requests_Write_Out.to_string()
		);
		CompleteStructHeader header_Requests_Write_Out;
		header_Requests_Write_Out =
		    TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Requests_Write_Out);
		CompleteStructMemberSeq member_seq_Requests_Write_Out;
		{
			TypeIdentifierPair type_ids_return_;
			ReturnCode_t return_code_return_{eprosima::fastdds::dds::RETCODE_OK};
			return_code_return_ = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			                          ->type_object_registry()
			                          .get_type_identifiers("cat::middleware::dds::TransferData", type_ids_return_);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_return_)
			{
				::cat::middleware::dds::register_TransferData_type_identifier(type_ids_return_);
			}
			StructMemberFlag member_flags_return_ = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false
			);
			MemberId member_id_return_ = 0x00000000;
			bool common_return__ec{false};
			CommonStructMember common_return_{TypeObjectUtils::build_common_struct_member(
			    member_id_return_,
			    member_flags_return_,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_return_, common_return__ec)
			)};
			if(!common_return__ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure return_ member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_return_ = "return_";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_return_;
			ann_custom_Requests_Write_Out.reset();
			CompleteMemberDetail detail_return_ = TypeObjectUtils::build_complete_member_detail(
			    name_return_, member_ann_builtin_return_, ann_custom_Requests_Write_Out
			);
			CompleteStructMember member_return_ =
			    TypeObjectUtils::build_complete_struct_member(common_return_, detail_return_);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Write_Out, member_return_);
		}
		CompleteStructType struct_type_Requests_Write_Out = TypeObjectUtils::build_complete_struct_type(
		    struct_flags_Requests_Write_Out, header_Requests_Write_Out, member_seq_Requests_Write_Out
		);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
		   TypeObjectUtils::build_and_register_struct_type_object(
		       struct_type_Requests_Write_Out, type_name_Requests_Write_Out.to_string(), type_ids_Requests_Write_Out
		   ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::detail::Requests_Write_Out already registered in TypeObjectRegistry for a "
			    "different type."
			);
		}
	}
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Requests_Write_Result_type_identifier(TypeIdentifierPair& type_ids_Requests_Write_Result)
{

	ReturnCode_t return_code_Requests_Write_Result{eprosima::fastdds::dds::RETCODE_OK};
	return_code_Requests_Write_Result =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::dds::detail::Requests_Write_Result", type_ids_Requests_Write_Result
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_Requests_Write_Result)
	{
		StructTypeFlag struct_flags_Requests_Write_Result = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::MUTABLE, false, false
		);
		QualifiedTypeName type_name_Requests_Write_Result = "cat::middleware::dds::detail::Requests_Write_Result";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Requests_Write_Result;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Requests_Write_Result;
		CompleteTypeDetail detail_Requests_Write_Result = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_Requests_Write_Result,
		    ann_custom_Requests_Write_Result,
		    type_name_Requests_Write_Result.to_string()
		);
		CompleteStructHeader header_Requests_Write_Result;
		header_Requests_Write_Result =
		    TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Requests_Write_Result);
		CompleteStructMemberSeq member_seq_Requests_Write_Result;
		{
			TypeIdentifierPair type_ids_result;
			ReturnCode_t return_code_result{eprosima::fastdds::dds::RETCODE_OK};
			return_code_result =
			    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			        ->type_object_registry()
			        .get_type_identifiers("cat::middleware::dds::detail::Requests_Write_Out", type_ids_result);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_result)
			{
				::cat::middleware::dds::detail::register_Requests_Write_Out_type_identifier(type_ids_result);
			}
			StructMemberFlag member_flags_result = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, true, false, false, false
			);
			MemberId member_id_result = 0x0784a8b4;
			bool common_result_ec{false};
			CommonStructMember common_result{TypeObjectUtils::build_common_struct_member(
			    member_id_result,
			    member_flags_result,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_result, common_result_ec)
			)};
			if(!common_result_ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure result member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_result = "result";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_result;
			ann_custom_Requests_Write_Result.reset();
			AppliedAnnotationSeq tmp_ann_custom_result;
			eprosima::fastcdr::optional<std::string> unit_result;
			eprosima::fastcdr::optional<AnnotationParameterValue> min_result;
			eprosima::fastcdr::optional<AnnotationParameterValue> max_result;
			eprosima::fastcdr::optional<std::string> hash_id_result;
			hash_id_result = "";

			if(unit_result.has_value() || min_result.has_value() || max_result.has_value() ||
			   hash_id_result.has_value())
			{
				member_ann_builtin_result = TypeObjectUtils::build_applied_builtin_member_annotations(
				    unit_result, min_result, max_result, hash_id_result
				);
			}
			if(!tmp_ann_custom_result.empty())
			{
				ann_custom_Requests_Write_Result = tmp_ann_custom_result;
			}
			CompleteMemberDetail detail_result = TypeObjectUtils::build_complete_member_detail(
			    name_result, member_ann_builtin_result, ann_custom_Requests_Write_Result
			);
			CompleteStructMember member_result =
			    TypeObjectUtils::build_complete_struct_member(common_result, detail_result);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Write_Result, member_result);
		}
		{
			TypeIdentifierPair type_ids_cat_middleware_dds_RequestException_ex;
			ReturnCode_t return_code_cat_middleware_dds_RequestException_ex{eprosima::fastdds::dds::RETCODE_OK};
			return_code_cat_middleware_dds_RequestException_ex =
			    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			        ->type_object_registry()
			        .get_type_identifiers(
			            "cat::middleware::dds::RequestException", type_ids_cat_middleware_dds_RequestException_ex
			        );

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_cat_middleware_dds_RequestException_ex)
			{
				::cat::middleware::dds::register_RequestException_type_identifier(
				    type_ids_cat_middleware_dds_RequestException_ex
				);
			}
			StructMemberFlag member_flags_cat_middleware_dds_RequestException_ex =
			    TypeObjectUtils::build_struct_member_flag(
			        eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, true, false, false, false
			    );
			MemberId member_id_cat_middleware_dds_RequestException_ex = 0x092eb941;
			bool common_cat_middleware_dds_RequestException_ex_ec{false};
			CommonStructMember common_cat_middleware_dds_RequestException_ex{
			    TypeObjectUtils::build_common_struct_member(
			        member_id_cat_middleware_dds_RequestException_ex,
			        member_flags_cat_middleware_dds_RequestException_ex,
			        TypeObjectUtils::retrieve_complete_type_identifier(
			            type_ids_cat_middleware_dds_RequestException_ex,
			            common_cat_middleware_dds_RequestException_ex_ec
			        )
			    )
			};
			if(!common_cat_middleware_dds_RequestException_ex_ec)
			{
				EPROSIMA_LOG_ERROR(
				    XTYPES_TYPE_REPRESENTATION,
				    "Structure cat_middleware_dds_RequestException_ex member TypeIdentifier inconsistent."
				);
				return;
			}
			MemberName name_cat_middleware_dds_RequestException_ex = "cat_middleware_dds_RequestException_ex";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations>
			    member_ann_builtin_cat_middleware_dds_RequestException_ex;
			ann_custom_Requests_Write_Result.reset();
			AppliedAnnotationSeq tmp_ann_custom_cat_middleware_dds_RequestException_ex;
			eprosima::fastcdr::optional<std::string> unit_cat_middleware_dds_RequestException_ex;
			eprosima::fastcdr::optional<AnnotationParameterValue> min_cat_middleware_dds_RequestException_ex;
			eprosima::fastcdr::optional<AnnotationParameterValue> max_cat_middleware_dds_RequestException_ex;
			eprosima::fastcdr::optional<std::string> hash_id_cat_middleware_dds_RequestException_ex;
			hash_id_cat_middleware_dds_RequestException_ex = "";

			if(unit_cat_middleware_dds_RequestException_ex.has_value() ||
			   min_cat_middleware_dds_RequestException_ex.has_value() ||
			   max_cat_middleware_dds_RequestException_ex.has_value() ||
			   hash_id_cat_middleware_dds_RequestException_ex.has_value())
			{
				member_ann_builtin_cat_middleware_dds_RequestException_ex =
				    TypeObjectUtils::build_applied_builtin_member_annotations(
				        unit_cat_middleware_dds_RequestException_ex,
				        min_cat_middleware_dds_RequestException_ex,
				        max_cat_middleware_dds_RequestException_ex,
				        hash_id_cat_middleware_dds_RequestException_ex
				    );
			}
			if(!tmp_ann_custom_cat_middleware_dds_RequestException_ex.empty())
			{
				ann_custom_Requests_Write_Result = tmp_ann_custom_cat_middleware_dds_RequestException_ex;
			}
			CompleteMemberDetail detail_cat_middleware_dds_RequestException_ex =
			    TypeObjectUtils::build_complete_member_detail(
			        name_cat_middleware_dds_RequestException_ex,
			        member_ann_builtin_cat_middleware_dds_RequestException_ex,
			        ann_custom_Requests_Write_Result
			    );
			CompleteStructMember member_cat_middleware_dds_RequestException_ex =
			    TypeObjectUtils::build_complete_struct_member(
			        common_cat_middleware_dds_RequestException_ex, detail_cat_middleware_dds_RequestException_ex
			    );
			TypeObjectUtils::add_complete_struct_member(
			    member_seq_Requests_Write_Result, member_cat_middleware_dds_RequestException_ex
			);
		}
		CompleteStructType struct_type_Requests_Write_Result = TypeObjectUtils::build_complete_struct_type(
		    struct_flags_Requests_Write_Result, header_Requests_Write_Result, member_seq_Requests_Write_Result
		);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER == TypeObjectUtils::build_and_register_struct_type_object(
		                                                        struct_type_Requests_Write_Result,
		                                                        type_name_Requests_Write_Result.to_string(),
		                                                        type_ids_Requests_Write_Result
		                                                    ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::detail::Requests_Write_Result already registered in TypeObjectRegistry for a "
			    "different type."
			);
		}
	}
}

//}  // Write

}  // namespace detail

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Requests_Request_type_identifier(TypeIdentifierPair& type_ids_Requests_Request)
{

	ReturnCode_t return_code_Requests_Request{eprosima::fastdds::dds::RETCODE_OK};
	return_code_Requests_Request =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::dds::detail::Requests_Request", type_ids_Requests_Request
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_Requests_Request)
	{
		StructTypeFlag struct_flags_Requests_Request = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::MUTABLE, false, false
		);
		QualifiedTypeName type_name_Requests_Request = "cat::middleware::dds::detail::Requests_Request";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Requests_Request;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Requests_Request;
		CompleteTypeDetail detail_Requests_Request = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_Requests_Request, ann_custom_Requests_Request, type_name_Requests_Request.to_string()
		);
		CompleteStructHeader header_Requests_Request;
		header_Requests_Request =
		    TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Requests_Request);
		CompleteStructMemberSeq member_seq_Requests_Request;
		{
			TypeIdentifierPair type_ids_Read;
			ReturnCode_t return_code_Read{eprosima::fastdds::dds::RETCODE_OK};
			return_code_Read =
			    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			        ->type_object_registry()
			        .get_type_identifiers("cat::middleware::dds::detail::Requests_Read_In", type_ids_Read);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_Read)
			{
				::cat::middleware::dds::detail::register_Requests_Read_In_type_identifier(type_ids_Read);
			}
			StructMemberFlag member_flags_Read = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, true, false, false, false
			);
			MemberId member_id_Read = 0x0e5f1a7a;
			bool common_Read_ec{false};
			CommonStructMember common_Read{TypeObjectUtils::build_common_struct_member(
			    member_id_Read,
			    member_flags_Read,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_Read, common_Read_ec)
			)};
			if(!common_Read_ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure Read member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_Read = "Read";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Read;
			ann_custom_Requests_Request.reset();
			AppliedAnnotationSeq tmp_ann_custom_Read;
			eprosima::fastcdr::optional<std::string> unit_Read;
			eprosima::fastcdr::optional<AnnotationParameterValue> min_Read;
			eprosima::fastcdr::optional<AnnotationParameterValue> max_Read;
			eprosima::fastcdr::optional<std::string> hash_id_Read;
			hash_id_Read = "";

			if(unit_Read.has_value() || min_Read.has_value() || max_Read.has_value() || hash_id_Read.has_value())
			{
				member_ann_builtin_Read = TypeObjectUtils::build_applied_builtin_member_annotations(
				    unit_Read, min_Read, max_Read, hash_id_Read
				);
			}
			if(!tmp_ann_custom_Read.empty())
			{
				ann_custom_Requests_Request = tmp_ann_custom_Read;
			}
			CompleteMemberDetail detail_Read = TypeObjectUtils::build_complete_member_detail(
			    name_Read, member_ann_builtin_Read, ann_custom_Requests_Request
			);
			CompleteStructMember member_Read = TypeObjectUtils::build_complete_struct_member(common_Read, detail_Read);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Request, member_Read);
		}
		{
			TypeIdentifierPair type_ids_Write;
			ReturnCode_t return_code_Write{eprosima::fastdds::dds::RETCODE_OK};
			return_code_Write =
			    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			        ->type_object_registry()
			        .get_type_identifiers("cat::middleware::dds::detail::Requests_Write_In", type_ids_Write);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_Write)
			{
				::cat::middleware::dds::detail::register_Requests_Write_In_type_identifier(type_ids_Write);
			}
			StructMemberFlag member_flags_Write = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, true, false, false, false
			);
			MemberId member_id_Write = 0x04c02911;
			bool common_Write_ec{false};
			CommonStructMember common_Write{TypeObjectUtils::build_common_struct_member(
			    member_id_Write,
			    member_flags_Write,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_Write, common_Write_ec)
			)};
			if(!common_Write_ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure Write member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_Write = "Write";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Write;
			ann_custom_Requests_Request.reset();
			AppliedAnnotationSeq tmp_ann_custom_Write;
			eprosima::fastcdr::optional<std::string> unit_Write;
			eprosima::fastcdr::optional<AnnotationParameterValue> min_Write;
			eprosima::fastcdr::optional<AnnotationParameterValue> max_Write;
			eprosima::fastcdr::optional<std::string> hash_id_Write;
			hash_id_Write = "";

			if(unit_Write.has_value() || min_Write.has_value() || max_Write.has_value() || hash_id_Write.has_value())
			{
				member_ann_builtin_Write = TypeObjectUtils::build_applied_builtin_member_annotations(
				    unit_Write, min_Write, max_Write, hash_id_Write
				);
			}
			if(!tmp_ann_custom_Write.empty())
			{
				ann_custom_Requests_Request = tmp_ann_custom_Write;
			}
			CompleteMemberDetail detail_Write = TypeObjectUtils::build_complete_member_detail(
			    name_Write, member_ann_builtin_Write, ann_custom_Requests_Request
			);
			CompleteStructMember member_Write =
			    TypeObjectUtils::build_complete_struct_member(common_Write, detail_Write);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Request, member_Write);
		}
		CompleteStructType struct_type_Requests_Request = TypeObjectUtils::build_complete_struct_type(
		    struct_flags_Requests_Request, header_Requests_Request, member_seq_Requests_Request
		);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
		   TypeObjectUtils::build_and_register_struct_type_object(
		       struct_type_Requests_Request, type_name_Requests_Request.to_string(), type_ids_Requests_Request
		   ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::detail::Requests_Request already registered in TypeObjectRegistry for a "
			    "different type."
			);
		}
	}
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Requests_Reply_type_identifier(TypeIdentifierPair& type_ids_Requests_Reply)
{

	ReturnCode_t return_code_Requests_Reply{eprosima::fastdds::dds::RETCODE_OK};
	return_code_Requests_Reply =
	    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
	        "cat::middleware::dds::detail::Requests_Reply", type_ids_Requests_Reply
	    );
	if(eprosima::fastdds::dds::RETCODE_OK != return_code_Requests_Reply)
	{
		StructTypeFlag struct_flags_Requests_Reply = TypeObjectUtils::build_struct_type_flag(
		    eprosima::fastdds::dds::xtypes::ExtensibilityKind::MUTABLE, false, false
		);
		QualifiedTypeName type_name_Requests_Reply = "cat::middleware::dds::detail::Requests_Reply";
		eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Requests_Reply;
		eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Requests_Reply;
		CompleteTypeDetail detail_Requests_Reply = TypeObjectUtils::build_complete_type_detail(
		    type_ann_builtin_Requests_Reply, ann_custom_Requests_Reply, type_name_Requests_Reply.to_string()
		);
		CompleteStructHeader header_Requests_Reply;
		header_Requests_Reply = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Requests_Reply);
		CompleteStructMemberSeq member_seq_Requests_Reply;
		{
			TypeIdentifierPair type_ids_Read;
			ReturnCode_t return_code_Read{eprosima::fastdds::dds::RETCODE_OK};
			return_code_Read =
			    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			        ->type_object_registry()
			        .get_type_identifiers("cat::middleware::dds::detail::Requests_Read_Result", type_ids_Read);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_Read)
			{
				::cat::middleware::dds::detail::register_Requests_Read_Result_type_identifier(type_ids_Read);
			}
			StructMemberFlag member_flags_Read = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, true, false, false, false
			);
			MemberId member_id_Read = 0x0e5f1a7a;
			bool common_Read_ec{false};
			CommonStructMember common_Read{TypeObjectUtils::build_common_struct_member(
			    member_id_Read,
			    member_flags_Read,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_Read, common_Read_ec)
			)};
			if(!common_Read_ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure Read member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_Read = "Read";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Read;
			ann_custom_Requests_Reply.reset();
			AppliedAnnotationSeq tmp_ann_custom_Read;
			eprosima::fastcdr::optional<std::string> unit_Read;
			eprosima::fastcdr::optional<AnnotationParameterValue> min_Read;
			eprosima::fastcdr::optional<AnnotationParameterValue> max_Read;
			eprosima::fastcdr::optional<std::string> hash_id_Read;
			hash_id_Read = "";

			if(unit_Read.has_value() || min_Read.has_value() || max_Read.has_value() || hash_id_Read.has_value())
			{
				member_ann_builtin_Read = TypeObjectUtils::build_applied_builtin_member_annotations(
				    unit_Read, min_Read, max_Read, hash_id_Read
				);
			}
			if(!tmp_ann_custom_Read.empty())
			{
				ann_custom_Requests_Reply = tmp_ann_custom_Read;
			}
			CompleteMemberDetail detail_Read = TypeObjectUtils::build_complete_member_detail(
			    name_Read, member_ann_builtin_Read, ann_custom_Requests_Reply
			);
			CompleteStructMember member_Read = TypeObjectUtils::build_complete_struct_member(common_Read, detail_Read);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Reply, member_Read);
		}
		{
			TypeIdentifierPair type_ids_Write;
			ReturnCode_t return_code_Write{eprosima::fastdds::dds::RETCODE_OK};
			return_code_Write =
			    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			        ->type_object_registry()
			        .get_type_identifiers("cat::middleware::dds::detail::Requests_Write_Result", type_ids_Write);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_Write)
			{
				::cat::middleware::dds::detail::register_Requests_Write_Result_type_identifier(type_ids_Write);
			}
			StructMemberFlag member_flags_Write = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, true, false, false, false
			);
			MemberId member_id_Write = 0x04c02911;
			bool common_Write_ec{false};
			CommonStructMember common_Write{TypeObjectUtils::build_common_struct_member(
			    member_id_Write,
			    member_flags_Write,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_Write, common_Write_ec)
			)};
			if(!common_Write_ec)
			{
				EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure Write member TypeIdentifier inconsistent.");
				return;
			}
			MemberName name_Write = "Write";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Write;
			ann_custom_Requests_Reply.reset();
			AppliedAnnotationSeq tmp_ann_custom_Write;
			eprosima::fastcdr::optional<std::string> unit_Write;
			eprosima::fastcdr::optional<AnnotationParameterValue> min_Write;
			eprosima::fastcdr::optional<AnnotationParameterValue> max_Write;
			eprosima::fastcdr::optional<std::string> hash_id_Write;
			hash_id_Write = "";

			if(unit_Write.has_value() || min_Write.has_value() || max_Write.has_value() || hash_id_Write.has_value())
			{
				member_ann_builtin_Write = TypeObjectUtils::build_applied_builtin_member_annotations(
				    unit_Write, min_Write, max_Write, hash_id_Write
				);
			}
			if(!tmp_ann_custom_Write.empty())
			{
				ann_custom_Requests_Reply = tmp_ann_custom_Write;
			}
			CompleteMemberDetail detail_Write = TypeObjectUtils::build_complete_member_detail(
			    name_Write, member_ann_builtin_Write, ann_custom_Requests_Reply
			);
			CompleteStructMember member_Write =
			    TypeObjectUtils::build_complete_struct_member(common_Write, detail_Write);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Reply, member_Write);
		}
		{
			TypeIdentifierPair type_ids_remoteEx;
			ReturnCode_t return_code_remoteEx{eprosima::fastdds::dds::RETCODE_OK};
			return_code_remoteEx =
			    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
			        ->type_object_registry()
			        .get_type_identifiers("eprosima::fastdds::dds::rpc::RemoteExceptionCode_t", type_ids_remoteEx);

			if(eprosima::fastdds::dds::RETCODE_OK != return_code_remoteEx)
			{
				::eprosima::fastdds::dds::rpc::register_RemoteExceptionCode_t_type_identifier(type_ids_remoteEx);
			}
			StructMemberFlag member_flags_remoteEx = TypeObjectUtils::build_struct_member_flag(
			    eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, true, false, false, false
			);
			MemberId member_id_remoteEx = 0x0f8e48f0;
			bool common_remoteEx_ec{false};
			CommonStructMember common_remoteEx{TypeObjectUtils::build_common_struct_member(
			    member_id_remoteEx,
			    member_flags_remoteEx,
			    TypeObjectUtils::retrieve_complete_type_identifier(type_ids_remoteEx, common_remoteEx_ec)
			)};
			if(!common_remoteEx_ec)
			{
				EPROSIMA_LOG_ERROR(
				    XTYPES_TYPE_REPRESENTATION, "Structure remoteEx member TypeIdentifier inconsistent."
				);
				return;
			}
			MemberName name_remoteEx = "remoteEx";
			eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_remoteEx;
			ann_custom_Requests_Reply.reset();
			AppliedAnnotationSeq tmp_ann_custom_remoteEx;
			eprosima::fastcdr::optional<std::string> unit_remoteEx;
			eprosima::fastcdr::optional<AnnotationParameterValue> min_remoteEx;
			eprosima::fastcdr::optional<AnnotationParameterValue> max_remoteEx;
			eprosima::fastcdr::optional<std::string> hash_id_remoteEx;
			hash_id_remoteEx = "";

			if(unit_remoteEx.has_value() || min_remoteEx.has_value() || max_remoteEx.has_value() ||
			   hash_id_remoteEx.has_value())
			{
				member_ann_builtin_remoteEx = TypeObjectUtils::build_applied_builtin_member_annotations(
				    unit_remoteEx, min_remoteEx, max_remoteEx, hash_id_remoteEx
				);
			}
			if(!tmp_ann_custom_remoteEx.empty())
			{
				ann_custom_Requests_Reply = tmp_ann_custom_remoteEx;
			}
			CompleteMemberDetail detail_remoteEx = TypeObjectUtils::build_complete_member_detail(
			    name_remoteEx, member_ann_builtin_remoteEx, ann_custom_Requests_Reply
			);
			CompleteStructMember member_remoteEx =
			    TypeObjectUtils::build_complete_struct_member(common_remoteEx, detail_remoteEx);
			TypeObjectUtils::add_complete_struct_member(member_seq_Requests_Reply, member_remoteEx);
		}
		CompleteStructType struct_type_Requests_Reply = TypeObjectUtils::build_complete_struct_type(
		    struct_flags_Requests_Reply, header_Requests_Reply, member_seq_Requests_Reply
		);
		if(eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
		   TypeObjectUtils::build_and_register_struct_type_object(
		       struct_type_Requests_Reply, type_name_Requests_Reply.to_string(), type_ids_Requests_Reply
		   ))
		{
			EPROSIMA_LOG_ERROR(
			    XTYPES_TYPE_REPRESENTATION,
			    "cat::middleware::dds::detail::Requests_Reply already registered in TypeObjectRegistry for a different "
			    "type."
			);
		}
	}
}

}  // namespace dds

}  // namespace middleware

}  // namespace cat
