// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file requestsClient.cxx
 * Client implementation for interfaces
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "requestsClient.hpp"

#include <atomic>
#include <exception>
#include <future>
#include <map>
#include <memory>
#include <mutex>
#include <queue>
#include <stdexcept>
#include <string>
#include <thread>

#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/domain/qos/RequesterQos.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/rpc/RequestInfo.hpp>
#include <fastdds/dds/rpc/Requester.hpp>
#include <fastdds/dds/rpc/Service.hpp>
#include <fastdds/dds/rpc/ServiceTypeSupport.hpp>
#include <fastdds/dds/rpc/exceptions.hpp>
#include <fastdds/dds/rpc/interfaces.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/rtps/common/Guid.hpp>
#include <fastdds/rtps/common/WriteParams.hpp>

#include "requests.hpp"
#include "requestsPubSubTypes.hpp"
#include "requests_details.hpp"

namespace cat
{

namespace middleware
{

namespace dds
{

//{ interface Requests

namespace detail
{

namespace fdds  = eprosima::fastdds::dds;
namespace frpc  = eprosima::fastdds::dds::rpc;
namespace frtps = eprosima::fastdds::rtps;

class RequestsClient : public Requests
{

	using RequestType = Requests_Request;
	using ReplyType   = Requests_Reply;

public:
	RequestsClient(fdds::DomainParticipant& part, char const* service_name, fdds::RequesterQos const& qos)
	    : Requests(), participant_(part)
	{
		// Register the service type support
		auto service_type = create_Requests_service_type_support();
		auto ret          = service_type.register_service_type(&participant_, "cat::middleware::dds::Requests");
		if(ret != fdds::RETCODE_OK)
		{
			throw std::runtime_error("Error registering service type");
		}

		// Create the service
		service_ = participant_.create_service(service_name, "cat::middleware::dds::Requests");
		if(nullptr == service_)
		{
			throw std::runtime_error("Error creating service");
		}

		// Create the requester
		requester_ = participant_.create_service_requester(service_, qos);
		if(nullptr == requester_)
		{
			throw std::runtime_error("Error creating requester");
		}

		// Start the processing thread
		start_thread();
	}

	~RequestsClient() override
	{
		// Stop the processing thread
		stop_thread();

		// Destroy the requester
		if(nullptr != requester_)
		{
			participant_.delete_service_requester(service_->get_service_name(), requester_);
			requester_ = nullptr;
		}

		// Destroy the service
		if(nullptr != service_)
		{
			participant_.delete_service(service_);
			service_ = nullptr;
		}
	}

private:
	void start_thread()
	{
		stop_thread_       = false;
		processing_thread_ = std::thread(&RequestsClient::run, this);
	}

	void stop_thread()
	{
		stop_thread_ = true;
		if(processing_thread_.joinable())
		{
			processing_thread_.join();
		}
	}

	void run()
	{
		while(!stop_thread_)
		{
			// Wait for a reply
			if(requester_->get_requester_reader()->wait_for_unread_message({0, 100000000}))
			{
				// Take and process the reply
				frpc::RequestInfo req_info;
				ReplyType reply;
				auto ret = requester_->take_reply(&reply, req_info);
				if(ret == fdds::RETCODE_OK)
				{
					process_reply(reply, req_info);
				}
			}
		}
	}

	void process_reply(ReplyType const& reply, frpc::RequestInfo const& req_info)
	{
		auto sample_id = req_info.related_sample_identity;
		{
			std::lock_guard<std::mutex> _(mtx_);
			auto it = pending_results_.find(sample_id);
			if(it != pending_results_.end())
			{
				bool should_erase = false;
				it->second->process_reply(reply, req_info, should_erase);
				if(should_erase)
				{
					pending_results_.erase(it);
				}
			}
		}
	}

	struct IReplyProcessor
	{
		frpc::RequestInfo info;

		virtual ~IReplyProcessor() = default;

		virtual void process_reply(ReplyType const& reply, frpc::RequestInfo const& req_info, bool& should_remove) = 0;
	};

	fdds::DomainParticipant& participant_;
	frpc::Service* service_     = nullptr;
	frpc::Requester* requester_ = nullptr;
	std::atomic<bool> stop_thread_{false};
	std::thread processing_thread_;
	std::mutex mtx_;
	std::map<frtps::SampleIdentity, std::shared_ptr<IReplyProcessor>> pending_results_;

	//{ request helpers

	template <typename T, typename TResult>
	std::future<TResult>
	send_request_with_promise(RequestType const& request, std::shared_ptr<T> result, std::promise<TResult>& promise)
	{
		result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
		{
			std::lock_guard<std::mutex> _(mtx_);
			if(fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
			{
				pending_results_[result->info.related_sample_identity] = result;
			}
			else
			{
				promise.set_exception(std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
			}
		}
		return promise.get_future();
	}

	template <typename T>
	std::shared_ptr<T> send_request_with_reader(RequestType const& request, std::shared_ptr<T> result)
	{
		result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
		{
			std::lock_guard<std::mutex> _(mtx_);
			if(fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
			{
				pending_results_[result->info.related_sample_identity] = result;
			}
			else
			{
				result->set_exception(std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
			}
		}
		return result;
	}

	//} request helpers

	//{ reply helpers

	template <typename T>
	static void set_invalid_reply(T& exception_receiver)
	{
		exception_receiver.set_exception(
		    std::make_exception_ptr(frpc::RemoteInvalidArgumentError("An invalid reply was received"))
		);
	}

	template <typename T>
	static void set_remote_exception(T& exception_receiver, frpc::RemoteExceptionCode_t const& exception)
	{
		switch(exception)
		{
			case frpc::RemoteExceptionCode_t::REMOTE_EX_OK: set_invalid_reply(exception_receiver); break;
			case frpc::RemoteExceptionCode_t::REMOTE_EX_UNSUPPORTED:
				exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnsupportedError()));
				break;
			case frpc::RemoteExceptionCode_t::REMOTE_EX_INVALID_ARGUMENT:
				exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteInvalidArgumentError()));
				break;
			case frpc::RemoteExceptionCode_t::REMOTE_EX_OUT_OF_RESOURCES:
				exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteOutOfResourcesError()));
				break;
			case frpc::RemoteExceptionCode_t::REMOTE_EX_UNKNOWN_OPERATION:
				exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownOperationError()));
				break;
			default:  // REMOTE_EX_UNKNOWN_EXCEPTION
				exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownExceptionError()));
				break;
		}
	}

	static size_t count_reply_fields(ReplyType const& reply)
	{
		size_t n_fields = 0;
		n_fields += reply.Read.has_value() ? 1 : 0;
		n_fields += reply.Write.has_value() ? 1 : 0;
		n_fields += reply.remoteEx.has_value() ? 1 : 0;
		return n_fields;
	}

	template <typename T>
	static bool validate_reply(std::promise<T>& promise, ReplyType const& reply)
	{
		// Check if the reply has one and only one field set
		size_t n_fields = count_reply_fields(reply);
		if(n_fields != 1u)
		{
			set_invalid_reply(promise);
			return false;
		}

		return true;
	}

	struct IExceptionHolder
	{
		virtual ~IExceptionHolder() = default;

		virtual void set_exception(std::exception_ptr exception) = 0;
	};

	static bool validate_reply(IExceptionHolder& reader, ReplyType const& reply)
	{
		// Check if the reply has one and only one field set
		size_t n_fields = count_reply_fields(reply);
		if(n_fields != 1u)
		{
			set_invalid_reply(reader);
			return false;
		}
		return true;
	}

	//} reply helpers

	//{ operation Read

public:
	eprosima::fastdds::dds::rpc::RpcFuture<cat::middleware::dds::TransferData> Read(
	    /*in*/ cat::middleware::dds::TransferData const& req
	) override
	{
		// Create a promise to hold the result
		auto result = std::make_shared<Read_promise>();

		// Create and send the request
		RequestType request;
		request.Read      = cat::middleware::dds::detail::Requests_Read_In{};
		request.Read->req = req;

		return send_request_with_promise(request, result, result->promise);
	}

private:
	struct Read_promise : public IReplyProcessor
	{
		std::promise<cat::middleware::dds::TransferData> promise;

		void process_reply(ReplyType const& reply, frpc::RequestInfo const& req_info, bool& should_remove) override
		{
			should_remove = false;
			if(req_info.related_sample_identity != info.related_sample_identity)
			{
				return;
			}

			should_remove = true;
			if(!validate_reply(promise, reply))
			{
				return;
			}

			if(reply.remoteEx.has_value())
			{
				set_remote_exception(promise, reply.remoteEx.value());
				return;
			}

			if(reply.Read.has_value())
			{
				auto const& result = reply.Read.value();
				if(result.result.has_value())
				{
					auto const& out = result.result.value();
					promise.set_value(out.return_);
					return;
				}
				if(result.cat_middleware_dds_RequestException_ex.has_value())
				{
					promise.set_exception(
					    std::make_exception_ptr(result.cat_middleware_dds_RequestException_ex.value())
					);
					return;
				}
			}

			// If we reach this point, the reply is for another operation
			set_invalid_reply(promise);
		}
	};

	//} operation Read

	//{ operation Write

public:
	eprosima::fastdds::dds::rpc::RpcFuture<cat::middleware::dds::TransferData> Write(
	    /*in*/ cat::middleware::dds::TransferData const& req
	) override
	{
		// Create a promise to hold the result
		auto result = std::make_shared<Write_promise>();

		// Create and send the request
		RequestType request;
		request.Write      = cat::middleware::dds::detail::Requests_Write_In{};
		request.Write->req = req;

		return send_request_with_promise(request, result, result->promise);
	}

private:
	struct Write_promise : public IReplyProcessor
	{
		std::promise<cat::middleware::dds::TransferData> promise;

		void process_reply(ReplyType const& reply, frpc::RequestInfo const& req_info, bool& should_remove) override
		{
			should_remove = false;
			if(req_info.related_sample_identity != info.related_sample_identity)
			{
				return;
			}

			should_remove = true;
			if(!validate_reply(promise, reply))
			{
				return;
			}

			if(reply.remoteEx.has_value())
			{
				set_remote_exception(promise, reply.remoteEx.value());
				return;
			}

			if(reply.Write.has_value())
			{
				auto const& result = reply.Write.value();
				if(result.result.has_value())
				{
					auto const& out = result.result.value();
					promise.set_value(out.return_);
					return;
				}
				if(result.cat_middleware_dds_RequestException_ex.has_value())
				{
					promise.set_exception(
					    std::make_exception_ptr(result.cat_middleware_dds_RequestException_ex.value())
					);
					return;
				}
			}

			// If we reach this point, the reply is for another operation
			set_invalid_reply(promise);
		}
	};

	//} operation Write
};

}  // namespace detail

std::shared_ptr<Requests> create_RequestsClient(
    eprosima::fastdds::dds::DomainParticipant& part,
    char const* service_name,
    eprosima::fastdds::dds::RequesterQos const& qos
)
{
	return std::make_shared<detail::RequestsClient>(part, service_name, qos);
}

//} interface RequestsClient

}  // namespace dds

}  // namespace middleware

}  // namespace cat
