// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file message.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__MESSAGE_HPP
#define FAST_DDS_GENERATED__MESSAGE_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MESSAGE_SOURCE)
#define MESSAGE_DllAPI __declspec(dllexport)
#else
#define MESSAGE_DllAPI __declspec(dllimport)
#endif  // MESSAGE_SOURCE
#else
#define MESSAGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MESSAGE_DllAPI
#endif  // _WIN32

/*!
 * @brief This class represents the structure Message defined by the user in the IDL file.
 * @ingroup message
 */
class Message
{
public:
	/*!
     * @brief Default constructor.
     */
	eProsima_user_DllExport Message()
	{
	}

	/*!
     * @brief Default destructor.
     */
	eProsima_user_DllExport ~Message()
	{
	}

	/*!
     * @brief Copy constructor.
     * @param x Reference to the object Message that will be copied.
     */
	eProsima_user_DllExport Message(Message const& x)
	{
		m_additional_information = x.m_additional_information;

		m_protobuf = x.m_protobuf;
	}

	/*!
     * @brief Move constructor.
     * @param x Reference to the object Message that will be copied.
     */
	eProsima_user_DllExport Message(Message&& x) noexcept
	{
		m_additional_information = std::move(x.m_additional_information);
		m_protobuf               = std::move(x.m_protobuf);
	}

	/*!
     * @brief Copy assignment.
     * @param x Reference to the object Message that will be copied.
     */
	eProsima_user_DllExport Message& operator=(Message const& x)
	{

		m_additional_information = x.m_additional_information;

		m_protobuf = x.m_protobuf;

		return *this;
	}

	/*!
     * @brief Move assignment.
     * @param x Reference to the object Message that will be copied.
     */
	eProsima_user_DllExport Message& operator=(Message&& x) noexcept
	{

		m_additional_information = std::move(x.m_additional_information);
		m_protobuf               = std::move(x.m_protobuf);
		return *this;
	}

	/*!
     * @brief Comparison operator.
     * @param x Message object to compare.
     */
	eProsima_user_DllExport bool operator==(Message const& x) const
	{
		return (m_additional_information == x.m_additional_information && m_protobuf == x.m_protobuf);
	}

	/*!
     * @brief Comparison operator.
     * @param x Message object to compare.
     */
	eProsima_user_DllExport bool operator!=(Message const& x) const
	{
		return !(*this == x);
	}

	/*!
     * @brief This function copies the value in member additional_information
     * @param _additional_information New value to be copied in member additional_information
     */
	eProsima_user_DllExport void additional_information(std::string const& _additional_information)
	{
		m_additional_information = _additional_information;
	}

	/*!
     * @brief This function moves the value in member additional_information
     * @param _additional_information New value to be moved in member additional_information
     */
	eProsima_user_DllExport void additional_information(std::string&& _additional_information)
	{
		m_additional_information = std::move(_additional_information);
	}

	/*!
     * @brief This function returns a constant reference to member additional_information
     * @return Constant reference to member additional_information
     */
	eProsima_user_DllExport const std::string& additional_information() const
	{
		return m_additional_information;
	}

	/*!
     * @brief This function returns a reference to member additional_information
     * @return Reference to member additional_information
     */
	eProsima_user_DllExport std::string& additional_information()
	{
		return m_additional_information;
	}

	/*!
     * @brief This function copies the value in member protobuf
     * @param _protobuf New value to be copied in member protobuf
     */
	eProsima_user_DllExport void protobuf(std::vector<uint8_t> const& _protobuf)
	{
		m_protobuf = _protobuf;
	}

	/*!
     * @brief This function moves the value in member protobuf
     * @param _protobuf New value to be moved in member protobuf
     */
	eProsima_user_DllExport void protobuf(std::vector<uint8_t>&& _protobuf)
	{
		m_protobuf = std::move(_protobuf);
	}

	/*!
     * @brief This function returns a constant reference to member protobuf
     * @return Constant reference to member protobuf
     */
	eProsima_user_DllExport const std::vector<uint8_t>& protobuf() const
	{
		return m_protobuf;
	}

	/*!
     * @brief This function returns a reference to member protobuf
     * @return Reference to member protobuf
     */
	eProsima_user_DllExport std::vector<uint8_t>& protobuf()
	{
		return m_protobuf;
	}

private:
	std::string m_additional_information;
	std::vector<uint8_t> m_protobuf;
};

#endif  // _FAST_DDS_GENERATED_MESSAGE_HPP_
